// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

use std::time::Instant;

fn main() {
  let start = Instant::now();

  let mut answer = 0; // Replace with your calculated answer
  let mut num1 = 1;
  let mut num2 = 2;
  while num2 < 4000000 {
    if num2 % 2 == 0 {
      answer += num2;
    }
    let next = num1 + num2;
    num1 = num2;
    num2 = next;
  }

  let duration = start.elapsed();
  println!("Problem 002: Answer = {}, Time: {:?}", answer, duration);
}
